### ISSUE TITLE
Strange Exception

### ISSUE THREAD

**Issue by neilchaudhuri** [chrisdinn/brando#64]
Do you know what might generate this exception? I am finding this using [play-redis](https://github.com/KarelCemus/play-redis), which has a dependency on brando, on Heroku.

`a.a.OneForOneStrategy - queue empty java.util.NoSuchElementException: queue empty at scala.collection.mutable.Queue.dequeue(Queue.scala:66) ~[org.scala-lang.scala-library-2.11.7.jar:na] 
at brando.Connection$$anonfun$receive$1$$anonfun$applyOrElse$4.apply(Connection.scala:91) ~[com.digital-achiever.brando_2.11-3.0.3.jar:3.0.3] 
at brando.Connection$$anonfun$receive$1$$anonfun$applyOrElse$4.apply(Connection.scala:78) ~[com.digital-achiever.brando_2.11-3.0.3.jar:3.0.3] 
at brando.ReplyParser$class.parseReply(ReplyParser.scala:145) ~[com.digital-achiever.brando_2.11-3.0.3.jar:3.0.3] at brando.Connection.parseReply(Connection.scala:27) ~[com.digital-achiever.brando_2.11-3.0.3.jar:3.0.3] 
at brando.Connection$$anonfun$receive$1.applyOrElse(Connection.scala:78) ~[com.digital-achiever.brando_2.11-3.0.3.jar:3.0.3] 
at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na] 
at brando.Connection.aroundReceive(Connection.scala:27) ~[com.digital-achiever.brando_2.11-3.0.3.jar:3.0.3] 
at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na] 
at akka.actor.ActorCell.invoke(ActorCell.scala:487) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]`

**Comment by KarelCemus** [comment]
Connected to [play-redis #29](https://github.com/KarelCemus/play-redis/issues/29). See for more detailed log and the use case description.

**Comment by damienlevin** [comment]
Is that something you can reproduce reliably ? If so, can you attach the associated Redis logs using [MONITOR](http://redis.io/commands/MONITOR) ?

Thanks

**Comment by neilchaudhuri** [comment]
Yes, I can reproduce this simply by deploying my application to Heroku. The application crashes with the error shown.

Unfortunately, the logs, which range from before and after the deployment, don't seem to show anything useful. But I am no Redis expert.

1449861962.904222 [0 10.146.17.183:49703] "PING"
1449861965.826261 [0 10.165.160.73:52908] "auth" "authvalue"
1449861965.827316 [0 10.165.160.73:52908] "client" "setname" "clientname"
1449861965.827922 [0 10.165.160.73:52908] "ping"
1449861967.892567 [0 10.146.17.183:49703] "PING"
1449861972.887725 [0 10.146.17.183:49703] "PING"
1449861977.880918 [0 10.146.17.183:49703] "PING"
1449861982.875982 [0 10.146.17.183:49703] "PING"
1449861987.908464 [0 10.146.17.183:49703] "PING"
1449861992.887900 [0 10.146.17.183:49703] "PING"
1449861994.092122 [0 10.16.208.172:39426] "auth" "authvalue"
1449861994.094457 [0 10.16.208.172:39426] "client" "setname" "clientname"
1449861994.096357 [0 10.16.208.172:39426] "ping"
1449861997.910047 [0 10.146.17.183:49703] "PING"
1449862002.933260 [0 10.146.17.183:49703] "PING"
1449862007.925935 [0 10.146.17.183:49703] "PING"
1449862013.004722 [0 10.146.17.183:49703] "PING"
1449862017.936156 [0 10.146.17.183:49703] "PING"
1449862018.161627 [0 10.146.17.183:49703] "INFO"
1449862019.839150 [0 10.165.160.73:57617] "auth" "authvalue"
1449862019.839779 [0 10.165.160.73:57617] "client" "setname" "clientname"
1449862019.841324 [0 10.165.160.73:57617] "ping"
1449862022.935898 [0 10.146.17.183:49703] "PING"
1449862027.906108 [0 10.146.17.183:49703] "PING"
1449862032.885646 [0 10.146.17.183:49703] "PING"

**Comment by neilchaudhuri** [comment]
I do see some "CLIENT" "SETNAME" "oracle" statements in the log. Since I wouldn't be caught dead using Oracle, I am not sure what that means or why that's showing up--or if it is even relevant. I am using the heroku-redis add-on (at the free level) if that means anything.

It is just really weird that this only yesterday started happening for me.

**Comment by KarelCemus** [comment]
Is there any progress with this issue? What the cause could be?

**Comment by KarelCemus** [comment]
Any thoughts about the cause? Is this major issue? Could you provide some explanation? Thanks.
